### ISSUE TITLE
V4EX-Coin [v1.0] 4.2. Mining Server Module

### ISSUE THREAD

**Issue by v4ex-inc** [v4ex/V4EX-Coin#3]
# 0. Purpose & Goals
1. Generate a mining task for miner.
2. Accept Social Proof of Work for checking.
3. Display countdown for required mining time.
4. Notify minter for finished mined task.

![MiningServer_Workflow r12](https://user-images.githubusercontent.com/77441151/126633763-21b6c650-12b9-403f-b95c-3e06ef075684.png)

# 1. Checklist
* [ ] 1.1. Miner **MUST** be able to finish required missions through Mining Server.
  - [x] 1.1.1. Miner **MUST** be able to **VIEW** the Mining Task. <sub>[wiki](https://github.com/v4ex/V4EX-Coin/wiki/Mining-Server#11-view)</sub>
  - [x] 1.1.2. Miner **MUST** be able to **INITIALIZE** the Mining Task. <sub>[wiki](https://github.com/v4ex/V4EX-Coin/wiki/Mining-Server#12-initialize)</sub>
  - [x] 1.1.3. Miner **MUST** be able to **REVERT_INITIALIZE** the Mining Task. <sub>[wiki](https://github.com/v4ex/V4EX-Coin/wiki/Mining-Server#13-revert_initialize)</sub>
  - [x] 1.1.4. Miner **MUST** be able to **EDIT** the Mining Task by sending work information. <sub>[wiki](https://github.com/v4ex/V4EX-Coin/wiki/Mining-Server#14-edit)</sub>
  - [x] 1.1.5. Miner **MUST** be able to **CLEAR_EDIT** the Mining Task. <sub>[wiki](https://github.com/v4ex/V4EX-Coin/wiki/Mining-Server#15-clear_edit)</sub>
  - [x] 1.1.6. Miner **MUST** be able to **SUBMIT** the Mining Task. <sub>[wiki](https://github.com/v4ex/V4EX-Coin/wiki/Mining-Server#16-submit)</sub>
  - [x] 1.1.7. Miner **MUST** be able to **REVERT_SUBMIT** the Mining Task. <sub>[wiki](https://github.com/v4ex/V4EX-Coin/wiki/Mining-Server#17-revert_submit)</sub>
  - [ ] 1.1.8. Miner **MAY** be able to **APPEAL** the Mining Task.
  - [ ] 1.1.9. Miner **MAY** be able to **RESTART** the Mining Task.
* [ ] 1.2. Broker **MUST** be able to finish required missions through Mining Server.
  - [x] 1.2.1. Broker **MUST** be able to **VIEW** the Mining Task of the specific Miner.
  - [x] 1.2.2. Broker **MUST** be able to **REJECT** the Mining Task of the specific Miner.
  - [x] 1.2.3. Broker **MUST** be able to **PROCEED** the Mining Task of the specific Miner.
  - [x] 1.2.4. Broker **MUST** be able to **RELEASE_MINER** the Mining Task of the specific Miner.
  - [x] 1.2.5. Broker **MUST** be able to **CONFIRM** the Mining Task of the specific Miner.
  - [x] 1.2.6. Broker **MUST** be able to **REVERT_CONFIRM** the Mining Task of the specific Miner.
  - [ ] 1.2.7. Broker **MAY** be able to **APPEAL** the Mining Task of the specific Miner.
* [ ] 1.3. Minter **MUST** be able to finish required missions through Mining Server.
  - [x] 1.3.1. Minter **MUST** be able to **VIEW** the Mining Task of the specific Miner.
  - [x] 1.3.2. Minter **MUST** be able to **DENY** the Mining Task of the specific Miner.
  - [x] 1.3.3. Minter **MUST** be able to **ADMIT** the Mining Task of the specific Miner.
  - [x] 1.3.4. Minter **MUST** be able to **RELEASE_BROKER** the Mining Task of the specific Miner to corresponding Broker.

### 1.1.1. Miner MUST be able to request to start a mining task.
* Page has a button for miner to start a mining task.
* [x] Miner Mining Service MUST prepare a mining task for the miner by requesting.
* [x] Miner Mining Service SHOULD provide a unique identity for the mining task.
* Page provides necessary instructions for how to do Social Proof of Work.
* Miner leaves the Page to Twitter.

## 1.1.2. Miner MUST be able to provide the mining task with Social Proof of Work for checking after doing it.
* Miner comes back to the Page after doing SPoW.
* Miner input the link of the tweet as SPoW in the Page.
* [x] Miner MUST be able to submit work details to Miner Mining Service.
* [x] Miner Mining Service MUST validate and store the submitted work details provided by Miner.
* Page notify miner with error message if SPoW check failed.

## 1.1.3. Miner MUST be able to check the status of the mining task.
* [x] Miner Mining Service MUST response mining task information if requested by the Miner.
* Page displays the countdown to finish the mining session if SPoW check passed.

# 2. Dependencies
* 2.1. #15
* 2.2. #13 
* 2.3. #11
* 2.4. #10

# 3. Specification
![Mining Session - Page 2](https://user-images.githubusercontent.com/77441151/123533333-01561280-d747-11eb-80a4-9499d63c1437.png)

URI: wss://coin.v4ex.com/mining?sub=${sub}

## 3.1. Miner Actions
* **VIEW**
* **INITIALIZE**
* **REVERT_INITIALIZE**
* **EDIT**
* **CLEAR_EDIT**
* **SUBMIT**
* **REVERT_SUBMIT**

## 3.2. Broker Actions
* **REJECT**
* **PROCEED**
* **RELEASE_MINER**
* **CONFIRM**
* **REVERT_CONFIRM**

## 3.3. Minter Actions
* **DENY**
* **ADMIT**
* **RELEASE_BROKER**

# C. Commits
* C.1. bde45600eb465bef60d83a977d9eee0ebe161799
* C.2. 4444e94f1fedb73d673e8e9d012816f511946cdc
* C.3. 2b91ca0fcd453ad1777320892d72070364bf0e13
* C.4. 5dde8565b11f00f9f1efd083fb189b9b905339e9
* C.5. 145483e2fade0792a542510e2b7535cf576f90df
* C.6. 553b756e6dd166237f01d6709bc685caab991613
* C.7. 2cc4d51f11ca87e84041c92597566b4a75f69824
* C.8. 0e7f9ec11252235f715da551adce4e7ed8f35a36
* C.9. 2bcf0d58423ba85a7f3639783cf93d61a5b3eab7
* C.10. 54d8fd2c3a5923651d39766207617a259dfbb41b
* C.11. f7b0ecad78433b6784dcd574ab23169fba50c182
* C.12. faff3c8bba93eedba86c360f866ee5c57ff05a68
* C.13. 95de52463a9587a4c39c46768fb872090f43380b
* C.14. 3a27de30cbc5ae50f2112b50c0d66bf6aeed4d97
* C15. d9ffd2d7522d66ffe6e8c07df34bb7a3955e624f
* C.16. f066abb6138e93962f471b30ec03bc62eaba22ff
* C.17. a73b88298f9383c73538354bf13c7c43a95f0efa
* C.18. 3b535047cfb776dec69a96382e3d133254349f15
* C.19. f846cab1814d5ce995ccaf291892f077930ad193
* C.20. 64bf3232c87a4dc369211ad4a0d262b3fc29566e
* C.21. fc7e8cd3b6f8b43abd42e836673e70bf1bb886d2
* C.22. 2432489b4646703730422538efe0662726ce24e1
* C.23. e541c2dbf431bde7ffaf18bbc59e69414acdcb6d
* C.24. 💪 ccdc6e6f580397faf26749100b708a0865cdeca4
  - Deprecating [src/api/mining.js](https://github.com/v4ex/V4EX-Coin/blob/ccdc6e6f580397faf26749100b708a0865cdeca4/src/api/mining.js)
  - Deprecating [src/api/mining/mining-task.js](https://github.com/v4ex/V4EX-Coin/blob/ccdc6e6f580397faf26749100b708a0865cdeca4/src/api/mining/mining-task.js)
  - Provide new set of files.
* C.25. 4ccc169eb4db5a2b08268a7d4f701dcf463b75fc
  - Initialize [src/web-socket-servers/mining/action.js](https://github.com/v4ex/V4EX-Coin/blob/4ccc169eb4db5a2b08268a7d4f701dcf463b75fc/src/web-socket-servers/mining/action.js)
  - Add ownership check to actions.
* C.26. be8df7808f050e6899189fa1ca0e7105332f690d
  - Refactor Mining Server according to new design which introducing Source, Resource concepts.
  - Source is a data source that utilize storage of Durable Object (Mining Server is a Durable Object acting as WebSocket Server).
  - Resource is hard coded role-based Wrapper for Source. Currently defined MinerMiningTask, BrokerMiningTask and MinterMiningTask MUST only include methods allowed by specific role.
  - Mining Server decide to pass which Resource to Action rely on Authorization role checking.
  - Refactor file structure from [src/web-socket-servers/mining](https://github.com/v4ex/V4EX-Coin/tree/4ccc169eb4db5a2b08268a7d4f701dcf463b75fc/src/web-socket-servers/mining) to [src/servers/mining](https://github.com/v4ex/V4EX-Coin/tree/be8df7808f050e6899189fa1ca0e7105332f690d/src/servers/mining)
* C.27. 9e54105058bb0b465575879c136e0cb14590f265
  - Deprecated [src/servers/mining/mining-task/resources/*](https://github.com/v4ex/V4EX-Coin/tree/be8df7808f050e6899189fa1ca0e7105332f690d/src/servers/mining/mining-task/resources), simplify logic.
  - [src/servers/mining/mining-task/mining-task-source.js](https://github.com/v4ex/V4EX-Coin/blob/be8df7808f050e6899189fa1ca0e7105332f690d/src/servers/mining/mining-task/mining-task-source.js) renamed to [src/servers/mining/mining-task/mining-task-resource.js](https://github.com/v4ex/V4EX-Coin/blob/9e54105058bb0b465575879c136e0cb14590f265/src/servers/mining/mining-task/mining-task-resource.js)
  - Adapt Action classes accordingly to new change.
  - Simplify [src/servers/mining/mining-server.js](https://github.com/v4ex/V4EX-Coin/blob/9e54105058bb0b465575879c136e0cb14590f265/src/servers/mining/mining-server.js) comparing to previous [src/servers/mining/mining-server.js](https://github.com/v4ex/V4EX-Coin/blob/be8df7808f050e6899189fa1ca0e7105332f690d/src/servers/mining/mining-server.js) in favor of WebSocket Server [new  design](https://github.com/v4ex/V4EX-Coin/blob/9e54105058bb0b465575879c136e0cb14590f265/src/servers/web-socket/web-socket-server.js#L129).
* C.28. c6e25408d85f51f3935898687753cf433262909b
* C.29. ac8a18b3036a2bd8da49f2337504b1ffd14fc2ca
  - Embed basic permissions control to Actions.
* C.30. 897e337d5189db3487b00038096553cf4a183eb3
  - Refactor Action.do() to Action.react().
  - Add some permissions checking.
* C.31. 2e50f8df10379a596e2ece6437c0fdbe3d008f03
  - Add [src/servers/mining/mining-task/actions/revert-initialize-action.js](https://github.com/v4ex/V4EX-Coin/blob/2e50f8df10379a596e2ece6437c0fdbe3d008f03/src/servers/mining/mining-task/actions/revert-initialize-action.js), [src/servers/mining/mining-task/actions/edit-action.js](https://github.com/v4ex/V4EX-Coin/blob/2e50f8df10379a596e2ece6437c0fdbe3d008f03/src/servers/mining/mining-task/actions/edit-action.js), [src/servers/mining/mining-task/actions/clear-edit-action.js](https://github.com/v4ex/V4EX-Coin/blob/2e50f8df10379a596e2ece6437c0fdbe3d008f03/src/servers/mining/mining-task/actions/clear-edit-action.js)
* C.32. beb674bb2f0c59f34b9e2b2355d9fa0d72caf741
  - Add [src/servers/mining/mining-task/actions/revert-submit-action.js](https://github.com/v4ex/V4EX-Coin/blob/beb674bb2f0c59f34b9e2b2355d9fa0d72caf741/src/servers/mining/mining-task/actions/revert-submit-action.js)
* C.33. 77c112c863cc067e61aae5792768f7adda38e368
  - Update MINING_TASK Actions.
* C.34. 766140f230d52e82c7da1a760c70783321172a8e
* C.35. f33d8f86ed29c1ce2a79690b2e184937098283e8
* C.36. 460f5b4f8e3be946224a87197fab6c78f33fb056
* C.37. e4b44cfb434a348aea2ae8a8863dadaf54cbf1d4
  - Update for ENV modification.
* C.38. c8bfea20fefb73da7b3ad83ad8f389a545737dd1
  - Update for introduction of broadcast watch.
* C.39. e578e60a286f736f8ab1064fee039c575f463d6c
  - Start moving User Permissions check logic into MiningTaskResource.
* C.40. 58cf42624c1cceb1a4e410f5e363d853b9ded7d1
  - Refactor Resource and Resource Actions to canUser*().

# F. Files
* F.1. [src/servers/mining/mining-server.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-server.js)
* F.2. [src/servers/mining/mining-task/mining-task-resource.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/mining-task-resource.js)
* F.3. [src/servers/mining/mining-task/models/mining-task.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/models/mining-task.js)
* F.4. [src/servers/mining/mining-task/actions/](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/)
  - F.4.1. [src/servers/mining/mining-task/actions/action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/action.js)
  - F.4.2. [src/servers/mining/mining-task/actions/initialize-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/initialize-action.js)
  - F.4.3. [src/servers/mining/mining-task/actions/revert-initialize-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/revert-initialize-action.js)
  - F.4.4. [src/servers/mining/mining-task/actions/edit-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/edit-action.js)
  - F.4.5. [src/servers/mining/mining-task/actions/clear-edit-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/clear-edit-action.js)
  - F.4.6. [src/servers/mining/mining-task/actions/submit-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/submit-action.js)
  - F.4.7. [src/servers/mining/mining-task/actions/revert-submit-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/revert-submit-action.js)
  - F.4.8. [src/servers/mining/mining-task/actions/reject-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/reject-action.js)
  - F.4.9. [src/servers/mining/mining-task/actions/proceed-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/proceed-action.js)
  - F.4.10. [src/servers/mining/mining-task/actions/release-miner-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/release-miner-action.js)
  - F.4.11. [src/servers/mining/mining-task/actions/confirm-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/confirm-action.js)
  - F.4.12. [src/servers/mining/mining-task/actions/revert-confirm-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/revert-confirm-action.js)
  - F.4.13. [src/servers/mining/mining-task/actions/deny-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/deny-action.js)
  - F.4.14. [src/servers/mining/mining-task/actions/admit-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/admit-action.js)
  - F.4.15. [src/servers/mining/mining-task/actions/release-broker-action.js](https://github.com/v4ex/V4EX-Coin/blob/v1.0/src/servers/mining/mining-task/actions/release-broker-action.js)

# R. References
* https://developers.cloudflare.com/workers/learning/using-durable-objects
* https://blog.cloudflare.com/introducing-workers-durable-objects/
* https://blog.cloudflare.com/introducing-cloudflare-workers/
* https://developer.mozilla.org/en-US/docs/Web/API
* https://developers.cloudflare.com/workers/
* https://www.cloudflare.com/learning/serverless/what-is-serverless/
* https://www.cloudflare.com/learning/serverless/glossary/function-as-a-service-faas/
* https://www.cloudflare.com/learning/serverless/glossary/what-is-edge-computing/
* https://www.cloudflare.com/learning/serverless/glossary/serverless-microservice/
* https://egghead.io/courses/build-a-serverless-api-with-cloudflare-workers-d67ca551
* https://blog.cloudflare.com/workers-kv-is-ga/
* https://blog.cloudflare.com/partnership-announcement-db/
* https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
* https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API
* https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
* https://github.com/cloudflare/workers-chat-demo
  - https://github.com/cloudflare/workers-types/issues/84
* :star: https://github.com/awthwathje/durable-objects-websocket-auth0-example
* https://rollupjs.org/
* https://developer.mozilla.org/en-US/docs/Web/API/Cache
* https://developers.cloudflare.com/workers/cli-wrangler/commands#kv
* https://developers.cloudflare.com/workers/get-started/quickstarts
* https://github.com/cloudflare/durable-objects-webpack-commonjs
* https://github.com/cloudflare/websocket-template
* https://developers.cloudflare.com/workers/cli-wrangler/configuration
* https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
* https://docs.npmjs.com/cli/v7/configuring-npm/package-json
* https://prettier.io/docs/en/configuration.html
* https://github.com/cloudflare/workers-graphql-server
* https://github.com/flareact/flareact
* https://github.com/flareact/flareact-template
* https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo
* https://github.com/cloudflare/durable-objects-template
* https://developers.cloudflare.com/workers/tutorials/authorize-users-with-auth0
* https://github.com/signalnerve/workers-auth0-example/
* https://github.com/auth0/auth0-react
* https://community.cloudflare.com/t/request-headers-comes-as-an-empty-object/181787
* https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api
* https://www.freecodecamp.org/news/how-to-secure-your-websocket-connections-d0be0996c556/
* https://developers.cloudflare.com/workers/cli-wrangler/commands
* https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation
* https://developers.cloudflare.com/workers/learning/debugging-workers
* https://www.w3schools.com/jsref/jsref_try_catch.asp
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static
* https://stackoverflow.com/questions/7615214/in-javascript-why-is-0-equal-to-false-but-when-tested-by-if-it-is-not-fals
* https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
* https://stackoverflow.com/questions/51467835/how-to-use-jsdoc-to-document-an-es6-class-property
* https://jsdoc.app/index.html
* https://code.visualstudio.com/docs/editor/intellisense
* https://marketplace.visualstudio.com/items?itemName=leizongmin.node-module-intellisense
* https://code.visualstudio.com/docs/getstarted/settings
* https://code.visualstudio.com/docs/languages/javascript
* https://github.com/microsoft/vscode/issues/35332
* https://github.com/microsoft/TypeScript/issues/10939
* 🩹 https://github.com/microsoft/TypeScript/issues/11367
* https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
* 👍 https://www.restapitutorial.com/httpstatuscodes.html
* https://www.npmjs.com/package/http-status
* https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
* https://www.npmjs.com/package/http-status-codes
* https://stackoverflow.com/questions/5101948/javascript-checking-for-null-vs-undefined-and-difference-between-and/5101991
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
* https://www.samanthaming.com/tidbits/70-3-ways-to-clone-objects/
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields
* 💥 https://webpack.js.org/configuration/output/#librarytarget-module
* https://nodejs.org/api/esm.html#esm_package_json_type_field
* https://fredriccliver.medium.com/syntaxerror-cannot-use-import-statement-outside-a-module-69182014b8c6
* https://www.asyncapi.com/
* https://www.openapis.org/
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
* https://github.com/APIDevTools
* https://openapi.tools/
* https://spec.openapis.org/oas/v3.1.0
* https://www.npmjs.com/package/@asyncapi/parser
* https://www.npmjs.com/package/asyncapi-validator
* 🥇 https://www.npmjs.com/package/ajv
* https://github.com/ajv-validator/ajv-formats
* https://ajv.js.org/guide/formats.html
* https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh
* https://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp
* https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02
* https://lodash.com/
* https://underscorejs.org/
* https://github.com/mozilla/source-map/
* 👍 https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh
* https://chrome.google.com/webstore/detail/websocket-test-client/fgponpodhbmadfljofbimhhlengambbn
* https://github.com/ajv-validator/ajv/issues/406
* https://github.com/eclipsesource/jsonforms/issues/1498
* https://github.com/cfworker/cfworker/tree/main/packages/json-schema
* https://www.npmjs.com/package/ws
* 👍 https://csprng.xyz/
* 👍 https://chrome.google.com/webstore/detail/talend-api-tester-free-ed/aejoelaoggembcahagimdiliamlcdmfm
* 👍 https://chrome.google.com/webstore/detail/websocket-king-client/cbcbkhdmedgianpaifchdaddpnmgnknn
* https://stackoverflow.com/questions/43431550/async-await-class-constructor
